services:
  db:
    image: postgres:15
    container_name: ecommerce_db
    environment:
      - POSTGRES_USER=ecommerce
      - POSTGRES_PASSWORD=ecommerce
      - POSTGRES_DB=ecommerce
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  
  frontend:
    image: grafana/grafana
    container_name: frontend
    environment:
      - GF_SECURITY_ADMIN_USER=ecommerce
      - GF_SECURITY_ADMIN_PASSWORD=ecommerce
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
  
volumes:
  pgdata:
  grafana_data: